import Head from 'next/head'

 const Home = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='bg-black'>
        <h1 className='text-2xl text-white'>Nabeel Portfolio</h1>
      </main>
    </>
  )
}

export default Home;
